# Generated by Django 5.0.4 on 2024-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('holidayStartingDay', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
