# Generated by Django 5.0.4 on 2024-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_employee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
