# Generated by Django 5.0.4 on 2024-05-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_alter_employee_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='PPR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
