# Generated by Django 3.2.25 on 2024-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_employee_ppr'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='isExiperd',
            field=models.BooleanField(default=False),
        ),
    ]
